# -*- coding: utf-8 -*-
"""AudioTranscription.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ll0XuqBIIoA70wuN2p7-eqGkHLP0Vk3z
"""

!pip install ibm_watson
!brew install ffmpeg

!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmped

!whisper "Small Talk.mp3" --model medium